import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>mm.omg.lol/now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          <a href="https://mm.omg.lol/now">mm.omg.lol/now</a>
        </h1>
      </main>
    </>
  );
}
