name: daily-cron
on:
  schedule:
    - cron: "0 1 * * *"
  push:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route
        run: |
          curl --request POST \
          --url 'https://automated-now-page.vercel.app/api/updatenowpage' \
          --header 'secret: ${{ secrets.API_SECRET_KEY }}'
